HOSTS:
  centos-66-x64:
    roles:
      - agent
      - default
    platform: el-6-x86_64
    box : puppetlabs/centos-6.6-64-puppet
    hypervisor : vagrant
CONFIG:
  type: foss
  vagrant_memsize: 1024
  log_level: verbose
